name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "projects/*/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
          fetch-depth: 3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
